# Generated by Django 6.0.3 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_flower_is_new_flower_is_popular_alter_flower_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='stock',
        ),
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.CharField(choices=[('romantic', 'Романтические'), ('wedding', 'Свадебные'), ('spring', 'Весенние'), ('birthday', 'День рождения'), ('business', 'Деловые')], default='romantic', max_length=50, verbose_name='Категория'),
        ),
    ]
